### ISSUE TITLE
Error when linting non-TS files 

### ISSUE THREAD

**Issue by P4** [DaveMBush/eslint-plugin-rxjs#13]
When I've added the plugin to my project using the `recommended` configuration as described in the README,
I got the following errors:

```
Error: Error while loading rule '@smarttools/rxjs/no-async-subscribe': You have used a rule which requires type information, but don't have parserOptions set to generate type information for this file. See https://typescript-eslint.io/getting-started/typed-linting for enabling linting with type information.
Parser: jsonc-eslint-parser
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.
Occurred while linting package.json
```

Seems to be because the recommended configuration applies the TS-specific rules for all files, but I have some linter rules enabled for JSON:
```js
const rxjs = require('@smarttools/eslint-plugin-rxjs');

module.exports = [
  // ...
  rxjs.configs.recommended,
  {
    files: ['**/*.ts'],
    languageOptions: {
      parserOptions: {
        projectService: true,
      },
    },
    plugins: {
      rxjs,
    },
  }
  // ...
  {
    files: ['**/*.json'],
    rules: {
      // ...
    },
    languageOptions: {
      parser: require('jsonc-eslint-parser'),
    },
  },
];
```

The same problem occurs for other non-TS languages too, if I disable the json config I get similar errors for HTML, etc.

In order for the plugin to work in this setup, I have to add it like this:
```js
  {
    files: ['**/*.ts'],
    ...rxjs.configs.recommended,
  },
```

Is there a way to include this into the config itself in a way that works for everybody?
Considering how many RxJS users are also Angular users and likely have `angular-eslint` configured for linting HTML templates, having the plugin work out of the box for multi-language setups would be really nice.

**Comment by DaveMBush** [comment]
Thanks for the feedback.

After careful consideration I've decided the best we can do here is make the documentation more clear about the need to configure eslint for type information and refer them to the eslint documentation on how to do this.

I don't know of any eslint rules that embed this information in the plugin and even if they did, there are multiple ways someone might configure eslint to do this and I'm sure if I were to embed it, someone would complain about the fact that I did that because it isn't typically (if ever) done.

I'll close this task and add another about updating the documentation.

**Comment by P4** [comment]
Thanks, the solution is fairly simple, so mentioning this in the docs is probably enough to guide someone towards it.

> I don't know of any eslint rules that embed this information in the plugin

Closest I could find is [a comment in Nx's default config for Angular](https://github.com/nrwl/nx/blob/0d6667d1566a88ebdbae0b65f73188fe95292cc2/packages/eslint-plugin/src/flat-configs/angular.ts#L18-L22), which is what I'm using in the project mentioned earlier.
